#!/bin/sh

set -Eeuo pipefail

function err {
  local stack_offset=1
  printf 'Failed build. Stacktrace:\n' >&2
  for stack_id in "${!FUNCNAME[@]}"; do
    if [[ "$stack_offset" -le "$stack_id" ]]; then
      local source_file="${BASH_SOURCE[$stack_id]}"
      local function="${FUNCNAME[$stack_id]}"
      local line="${BASH_LINENO[$(( stack_id - 1 ))]}"
      >&2 printf '\t%s:%s:%s\n' "$source_file" "$function" "$line"
    fi
  done
}

trap 'err' ERR


CONT_NAME="dd_temp"
echo "HOST_UID=${HOST_UID:=`id -u`}"
echo "HOST_GID=${HOST_GID:=`id -g`}"

docker stop ${CONT_NAME} || echo "not running, skipping..."
docker rm ${CONT_NAME} || echo "not running, skipping..."

docker build -t e - < Dockerfile

docker run -it \
  --name ${CONT_NAME} \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --mount type=bind,source=/home/mkoldych/d,target=/home/${USER}/d,readonly \
  --mount type=bind,source=/home/mkoldych/stow,target=/home/${USER}/stow,readonly \
  -d e
if [ $? -ne 0 ]
then
  echo "ERROR: Failed to run docker"
  exit 1
fi

docker exec -it \
    ${CONT_NAME} \
    /home/${USER}/d/setup_internal ${HOST_UID} ${HOST_GID}
if [[ $? != 0 ]]; then
    echo "Failed to setup container"
    exit 1
fi

docker exec -it \
	-u ${HOST_UID}:${HOST_GID} \
	${CONT_NAME} \
	/home/${USER}/d/init
if [ $? -ne 0 ]
then
  echo "ERROR: Failed to run init"
  exit 1
fi

docker commit ${CONT_NAME} e

docker stop ${CONT_NAME}
docker rm ${CONT_NAME}
