#!/bin/bash

set -Eeuo pipefail

function err {
  local stack_offset=1
  printf 'Failed init. Stacktrace:\n' >&2
  for stack_id in "${!FUNCNAME[@]}"; do
    if [[ "$stack_offset" -le "$stack_id" ]]; then
      local source_file="${BASH_SOURCE[$stack_id]}"
      local function="${FUNCNAME[$stack_id]}"
      local line="${BASH_LINENO[$(( stack_id - 1 ))]}"
      >&2 printf '\t%s:%s:%s\n' "$source_file" "$function" "$line"
    fi
  done
}

trap 'err' ERR

cd
mkdir -p .config/nvim
mkdir -p .vim
cd stow/packages
stow -t ../../ readline
stow -t ../../ vim
stow -t ../../ nvim

cd /usr/local/src
sudo git clone https://github.com/microsoft/vcpkg
sudo ./vcpkg/bootstrap-vcpkg.sh
./vcpkg/vcpkg integrate install
sudo ./vcpkg/vcpkg install jsoncpp


cd /usr/local/src
sudo git clone https://github.com/google/googletest.git
cd googletest
sudo mkdir build
cd build
sudo cmake ..
sudo make
sudo make install

