#!/bin/bash

set -Eeuo pipefail

function err {
  local stack_offset=1
  printf 'Failed run. Stacktrace:\n' >&2
  for stack_id in "${!FUNCNAME[@]}"; do
    if [[ "$stack_offset" -le "$stack_id" ]]; then
      local source_file="${BASH_SOURCE[$stack_id]}"
      local function="${FUNCNAME[$stack_id]}"
      local line="${BASH_LINENO[$(( stack_id - 1 ))]}"
      >&2 printf '\t%s:%s:%s\n' "$source_file" "$function" "$line"
    fi
  done
}

trap 'err' ERR

CONT_NAME="gg"
IMAGE_NAME="g"

docker rm -f ${CONT_NAME} || echo "not running, skipping..."

#    --pid="host" \
#  -u $(id -u):$(id -g) \
docker run -it \
  --name ${CONT_NAME} \
  -u $(id -u) \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --network host \
  --mount type=bind,source=/localdisk,target=/localdisk \
  --mount type=bind,source=/corp/sta,target=/corp/sta \
  --mount type=bind,source=/home/${USER}/d,target=/home/${USER}/d \
  --mount type=bind,source=/home/${USER}/stow,target=/home/${USER}/stow \
  --mount type=bind,source=/home/${USER}/.gitconfig,target=/home/${USER}/.gitconfig \
  --mount type=bind,source=/home/${USER}/.gitignore,target=/home/${USER}/.gitignore \
  --mount type=bind,source=/home/${USER}/.zshrc,target=/home/${USER}/.zshrc \
  --mount type=bind,source=/home/${USER}/.zshrc.zni,target=/home/${USER}/.zshrc.zni \
  --mount type=bind,source=/home/${USER}/.zsh-settings,target=/home/${USER}/.zsh-settings \
  --mount type=bind,source=/home/${USER}/.ssh,target=/home/${USER}/.ssh \
  -d ${IMAGE_NAME}
if [ $? -ne 0 ]
then
  echo "ERROR: Failed to run docker"
  exit 1
fi

docker exec -it ${CONT_NAME} zsh
