#!/bin/bash

set -Eeuo pipefail

function err {
  local stack_offset=1
  printf 'Failed run. Stacktrace:\n' >&2
  for stack_id in "${!FUNCNAME[@]}"; do
    if [[ "$stack_offset" -le "$stack_id" ]]; then
      local source_file="${BASH_SOURCE[$stack_id]}"
      local function="${FUNCNAME[$stack_id]}"
      local line="${BASH_LINENO[$(( stack_id - 1 ))]}"
      >&2 printf '\t%s:%s:%s\n' "$source_file" "$function" "$line"
    fi
  done
}

trap 'err' ERR


#    --pid="host" \

CONT_NAME="dd"

docker stop ${CONT_NAME} || echo "not running, skipping..."
docker rm ${CONT_NAME} || echo "not running, skipping..."

docker run -it \
  --name ${CONT_NAME} \
  -u $(id -u):$(id -g) \
  --mount type=bind,source=/localdisk,target=/localdisk \
  --mount type=bind,source=/home/${USER}/d,target=/home/${USER}/d,readonly \
  --mount type=bind,source=/home/${USER}/stow,target=/home/${USER}/stow,readonly \
  --mount type=bind,source=/home/${USER}/.gitconfig,target=/home/${USER}/.gitconfig,readonly \
  --mount type=bind,source=/home/${USER}/.gitignore,target=/home/${USER}/.gitignore,readonly \
  --mount type=bind,source=/home/${USER}/.zshrc,target=/home/${USER}/.zshrc,readonly \
  --mount type=bind,source=/home/${USER}/.zshrc.zni,target=/home/${USER}/.zshrc.zni,readonly \
  --mount type=bind,source=/home/${USER}/.zsh-settings,target=/home/${USER}/.zsh-settings,readonly \
  -d d
if [ $? -ne 0 ]
then
  echo "ERROR: Failed to run docker"
  exit 1
fi

docker exec -it ${CONT_NAME} zsh
