#!/bin/bash

set -Eeuo pipefail
set -o xtrace

#    --pid="host" \

CONT_NAME="dd"

docker stop ${CONT_NAME} || echo "not running, skipping..."
docker rm ${CONT_NAME} || echo "not running, skipping..."

docker run -it \
  --name ${CONT_NAME} \
  -u $(id -u):$(id -g) \
  --mount type=bind,source=/localdisk,target=/localdisk \
  --mount type=bind,source=/home/mkoldych/d,target=/home/mkoldych/d,readonly \
  --mount type=bind,source=/home/mkoldych/stow,target=/home/mkoldych/stow,readonly \
  --mount type=bind,source=/home/mkoldych/.zshrc,target=/home/mkoldych/.zshrc,readonly \
  --mount type=bind,source=/home/mkoldych/.zshrc.zni,target=/home/mkoldych/.zshrc.zni,readonly \
  --mount type=bind,source=/home/mkoldych/.zsh-settings,target=/home/mkoldych/.zsh-settings,readonly \
  -d d
if [ $? -ne 0 ]
then
  echo "ERROR: Failed to run docker"
  exit 1
fi

docker exec -it ${CONT_NAME} zsh
