#!/bin/bash

set -Eeuo pipefail

function err {
  local stack_offset=1
  printf 'Failed internal setup. Stacktrace:\n' >&2
  for stack_id in "${!FUNCNAME[@]}"; do
    if [[ "$stack_offset" -le "$stack_id" ]]; then
      local source_file="${BASH_SOURCE[$stack_id]}"
      local function="${FUNCNAME[$stack_id]}"
      local line="${BASH_LINENO[$(( stack_id - 1 ))]}"
      >&2 printf '\t%s:%s:%s\n' "$source_file" "$function" "$line"
    fi
  done
}

trap 'err' ERR

# Setup user and group and allow sudo without password
useradd hostuser -m -u ${1} -g root -s /bin/bash

groupadd -g ${2} hostgroup
usermod -a -G hostgroup hostuser
cat << EOF > /etc/sudoers.d/host
%hostgroup   ALL=(ALL:ALL) NOPASSWD: ALL
EOF

# Setup docker group to allow docker without sudo
groupadd -g $(ls -l /var/run/docker.sock | awk '{print $4}') hostdocker
usermod -a -G hostdocker hostuser

cd ${HOME}
sudo chown ${1}:${2} .
sudo chown -R ${1}:${2} $(ls -a -I .. -I . -I d -I stow)
#chmod a+rwx /tmp
#chmod a+rwx /var/log
