set nocompatible              " be iMproved, required
filetype off                  " required


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""""""""""" CSCOPE """""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""




"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""""""""""" REGULAR VIM STUFF """"""""""""""""""""""""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
filetype plugin indent on
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set hlsearch
set incsearch

set mouse=a
colorscheme elflord

highlight Visual cterm=reverse ctermbg=NONE


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""""""""""" TAB NAVIGATION """""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""
nnoremap th :tabfirst<CR>
nnoremap tk :tabnext<CR>
nnoremap tj :tabprev<CR>
nnoremap tl :tablast<CR>
nnoremap tt :tabedit<Space>
nnoremap tm :tabm<Space>
nnoremap td :tabclose<CR>
nnoremap tn :tabnew<CR>

nnoremap <leader>1 1gt
nnoremap <leader>2 2gt
nnoremap <leader>3 3gt
nnoremap <leader>4 4gt
nnoremap <leader>5 5gt
nnoremap <leader>6 6gt
nnoremap <leader>7 7gt
nnoremap <leader>8 8gt
nnoremap <leader>9 9gt
nnoremap <leader>0 10gt
